#!/bin/bash

#SBATCH -n 72
#SBATCH -N 1
#SBATCH --partition=medium
##SBATCH --partition=priority-mem768
#SBATCH --qos=maizegdb
#SBATCH --mem=200G
#SBATCH --time=7-00:00:00
#SBATCH --job-name="sd_Sg"
#SBATCH --mail-user=sagnikbanerjee15@gmail.com
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/Sg.output 
#SBATCH --error=/project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/Sg.error

module load singularity
FUNGAL_SPECIES="Sg"
mkdir -p /project/maizegdb/sagnik/3_fungal_genomes/${FUNGAL_SPECIES}/soapdenovo2/soapdenovo2/${FUNGAL_SPECIES}


################################################################################################################################################################
# Perform genome assembly
################################################################################################################################################################

if [ ! -f /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/masurca/${FUNGAL_SPECIES}/primary.genome.scf.fasta ]
then
	cwltool \
	--singularity \
	--outdir /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES} \
	/project/maizegdb/sagnik/tools_and_pipelines/soapdenovo2/2.04/generate_config_file_and_assemble.cwl \
	--cpu 72 \
	--directory_with_input_reads /project/maizegdb/sagnik/3_fungal_genomes/DNA-seq/${FUNGAL_SPECIES} \
	1> /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_assembly.output \
	2> /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_assembly.error
fi

################################################################################################################################################################
# Align RNA-Seq reads to the assembled genome
################################################################################################################################################################

if [ ! -f /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/masurca/${FUNGAL_SPECIES}_rna_seq_alignments/merged_1_possorted.bam ]
then 
	cwltool \
	--singularity \
	--outdir /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_rna_seq_alignments \
	/project/maizegdb/sagnik/tools_and_pipelines/star/2.7.9a/star_generate_index_and_align.cwl \
	--threads 72 \
	--reference /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}/soapdenovo127mer_output.scafSeq \
	--raw_input_files_pair1 /project/maizegdb/sagnik/3_fungal_genomes/RNA-seq/${FUNGAL_SPECIES}/merged_1.fastq \
	--raw_input_files_pair2 /project/maizegdb/sagnik/3_fungal_genomes/RNA-seq/${FUNGAL_SPECIES}/merged_2.fastq \
	1> /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_rna_seq_alignments.output \
	2> /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_rna_seq_alignments.error
fi

################################################################################################################################################################
# Align DNA-Seq reads to the assembled genome
################################################################################################################################################################

if [ ! -f /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_dna_seq_alignments/bowtie2_align.output ]
then 
	cwltool \
	--singularity \
	--outdir /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_dna_seq_alignments \
	/project/maizegdb/sagnik/tools_and_pipelines/bowtie2/2.4.5/bowtie_create_index_and_align.cwl \
	--threads 72 \
	--reference /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}/soapdenovo127mer_output.scafSeq  \
	--mate1 /project/maizegdb/sagnik/3_fungal_genomes/DNA-seq/${FUNGAL_SPECIES}/merged_1.fastq \
	--mate2 /project/maizegdb/sagnik/3_fungal_genomes/DNA-seq/${FUNGAL_SPECIES}/merged_2.fastq \
	--max_number_of_multple_alignments 1000 \
	1> /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_dna_seq_alignments.output \
	2> /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_dna_seq_alignments.error
fi

################################################################################################################################################################
# Execute FGMP on the assembled genome
################################################################################################################################################################

if [ ! -f /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_fgmp/primary.genome.scf.fasta.unfiltered.renamed.hmmsearch.summary_report ]
then 
	cwltool \
	--singularity \
	--outdir /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_fgmp \
	/project/maizegdb/sagnik/tools_and_pipelines/fgmp/1.0.3/assess_quality_fgmp.cwl \
	--threads 72 \
	--genome_fastafile /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}/soapdenovo127mer_output.scafSeq \
	1> /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_fgmp.output \
	2> /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_fgmp.error
fi

################################################################################################################################################################
# Execute BUSCO on the assembled genome
################################################################################################################################################################
if [ ! -f /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_busco/full_table.tsv ]
then 
	cwltool \
	--singularity \
	--outdir /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_busco \
	/project/maizegdb/sagnik/tools_and_pipelines/busco/5.4.5/busco_fungal_genome_assembly_qc.cwl \
	--threads 72 \
	--reference /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}/soapdenovo127mer_output.scafSeq \
	1> /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_busco.output \
	2> /project/maizegdb/sagnik/3_fungal_genomes/genome_assembly/soapdenovo2/${FUNGAL_SPECIES}_busco.error
fi