#!/bin/bash

#SBATCH --nodes=1 # request one node
#SBATCH --cpus-per-task=150  
#SBATCH --mem=1500G # Maximum amount of memory this job will be given, try to estimate this to the best of your ability. This asks for 128 GB of ram.
#SBATCH --partition=bigram
#SBATCH --time=100:00:00
#SBATCH --job-name="3FG_2_spades" 
#SBATCH --mail-user=sagnik@iastate.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/spades_assembly/abyss_assemble_Sample_2.output
#SBATCH --error=/work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/spades_assembly/abyss_assemble_Sample_2.error 

conda activate masurca

mkdir -p /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/spades_assembly
cd /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/spades_assembly

spades.py -k 15,25,35,45,55,65,75,85,95,105,115,125 \
-t 150 \
--pe1-1 /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/2_S2_L001_cov_paired_trim_R1_001.fastq \
--pe1-2 /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/2_S2_L001_cov_paired_trim_R2_001.fastq \
--pe1-1 /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/2_S2_L001_enz_paired_trim_R1_001.fastq \
--pe1-2 /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/2_S2_L001_enz_paired_trim_R2_001.fastq \
--pe1-1 /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/65_S65_paired_trim_R1.fastq \
--pe1-2 /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/65_S65_paired_trim_R2.fastq \
--pe1-1 /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/68_S68_paired_trim_R1.fastq \
--pe1-2 /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/68_S68_paired_trim_R2.fastq \
-o /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/spades_assembly \
> /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/spades_assembly.output \
2> /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/spades_assembly.error

