#!/bin/bash

#SBATCH --nodes=1 # request one node
#SBATCH --cpus-per-task=150  
#SBATCH --mem=1500G # Maximum amount of memory this job will be given, try to estimate this to the best of your ability. This asks for 128 GB of ram.
#SBATCH --partition=bigram
#SBATCH --time=100:00:00
#SBATCH --job-name="3FG_2" 
#SBATCH --mail-user=sagnik@iastate.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/abyss_assembly/abyss_assemble_Sample_2.output
#SBATCH --error=/work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/abyss_assembly/abyss_assemble_Sample_2.error 

conda activate masurca

mkdir -p /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/abyss_assembly
cd /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/abyss_assembly

for k in `seq 50 10 100`; do
	mkdir k$k
	nohup abyss-pe -j 30 k=$k -C k$k name=Sample_2 lib='peh1 peh2 pem1 pem2' peh1='/work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/65_S65_paired_trim_R1.fastq  /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/65_S65_paired_trim_R2.fastq' peh2='/work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/68_S68_paired_trim_R1.fastq  /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/68_S68_paired_trim_R2.fastq' pem1='/work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/2_S2_L001_cov_paired_trim_R1_001.fastq /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/2_S2_L001_cov_paired_trim_R2_001.fastq' pem2='/work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/2_S2_L001_enz_paired_trim_R1_001.fastq /work/LAS/rpwise-lab/sagnik/3FG/data/Sample_2/2_S2_L001_enz_paired_trim_R2_001.fastq' > k$k.output 2> k$k.error &
done
abyss-fac k*/ecoli-contigs.fa 

