#!/usr/bin/env python3

##############################################################################################################################
#
#
##############################################################################################################################
from argparse import RawTextHelpFormatter

import os
import glob
import argparse
import sys
import math

def parseCommandLineArguments():

    parser = argparse.ArgumentParser( prog = "decompress_and_scaffold_using_rascaf", description = """Decompress each assembly, scaffold using rascaf and compress all the outputs""", formatter_class = RawTextHelpFormatter )

    parser.add_argument( "--compressed_assembly_file_from_abyss", help = "Enter the compressed assembly file", required = True )
    parser.add_argument( "--left_fastq", help = "Enter the left fastq file", required = True )
    parser.add_argument( "--right_fastq", help = "Enter the right fastq file", required = True )
    parser.add_argument( "--output_filename", help = "Enter the name of the outputfile in csv", required = True )
    
    parser.add_argument( "--threads", type = int, default = 1)
    return parser.parse_args()

def calculateParametersForSTARIndexGeneration(filename):
    
    fhr = open(filename,"r")
    num_chromosomes = 0
    reference_length = 0
    for line in fhr:
        if line[0]=='>':
            num_chromosomes+=1
        else:
            reference_length+=len(line.strip())
    fhr.close()
    
    genomeSAindexNbases = int(min(14, math.log2(reference_length)/2 - 1))
    genomeChrBinNbits = int(min(18,math.log2(reference_length/num_chromosomes)))
    
    return genomeSAindexNbases, genomeChrBinNbits

def main():
    """
    """
    options = parseCommandLineArguments()
    
    # Expand abyss assemblies
    cmd = f"tar -xvhf {options.compressed_assembly_file_from_abyss}"
    os.system(cmd)
    
    # Collect the abyss assemblies
    abyss_assemblies  = glob.glob("*-contigs.fa")
    
    # Scaffold each assembly
    files_for_compression = []
    for abyss_assembly in abyss_assemblies:
        k, kc = abyss_assembly.split("/")[-1].split("_")[2], abyss_assembly.split("/")[-1].split("_")[3].split("-")[0]
        
        genomeSAindexNbases, genomeChrBinNbits = calculateParametersForSTARIndexGeneration(abyss_assembly)
        cmd  = "STAR"
        cmd += f" --runMode genomeGenerate"
        cmd += f" --genomeDir star_index"
        cmd += f" --genomeSAindexNbases {genomeSAindexNbases}"
        cmd += f" --genomeChrBinNbits {genomeChrBinNbits}"
        cmd += f" --runThreadN {options.threads}"
        cmd += f" --genomeFastaFiles {abyss_assembly}"
        os.system(cmd)
        
        cmd  = f" STAR "
        cmd += f" --genomeDir star_index "
        cmd += f" --alignIntronMax 10000"
        cmd += f" --outFilterMultimapNmax 500"
        cmd += f" --alignIntronMin 20"
        cmd += f" --outSAMtype BAM SortedByCoordinate"
        cmd += f" --outFileNamePrefix abyss_"
        cmd += f" --limitBAMsortRAM 1000712700 "
        cmd += f" --runThreadN {options.threads}"
        cmd += f" --readFilesIn {options.left_fastq} {options.right_fastq} "
        os.system(cmd)
        
        cmd  = f" rascaf "
        cmd += f" -b abyss_Aligned.sortedByCoord.out.bam "
        cmd += f" -f {abyss_assembly} "
        cmd += f" -o rascaf"
        os.system(cmd)
        
        cmd  = f"rascaf-join "
        cmd += f" -r rascaf.out "
        cmd += f" -o abyss_{k}_{kc}_rascaf"
        os.system(cmd)
    
        """cmd = f"mv p_rna_scaffolder_output/P_RNA_scaffold.fasta abyss_assembly_{k}_{kc}_p_rna_scaffolder.fasta"
        os.system(cmd)"""
    
    cmd = f"tar -cvhf {options.output_filename} abyss_*rascaf*fa"
    os.system(cmd)

if __name__ == "__main__":
    main()