#!/usr/bin/env python3

##############################################################################################################################
#
#
##############################################################################################################################
from argparse import RawTextHelpFormatter

import os
import glob
import argparse
import sys

def parseCommandLineArguments():

    parser = argparse.ArgumentParser( prog = "execute_FGMP_and_compile_single_output_file", description = """Run FGMP on each file and compile a single output file""", formatter_class = RawTextHelpFormatter )

    parser.add_argument( "--masurca_with_rascaf", help = "Enter the output for masurca with rascaf", required = True )
    parser.add_argument( "--masurca_with_prna_scaffolder", help = "Enter the output for masurca with prna scaffolder", required = True )
    
    parser.add_argument( "--megahit_with_rascaf", help = "Enter the output for masurca with rascaf", required = True )
    parser.add_argument( "--megahit_with_prna_scaffolder", help = "Enter the output for megahit with prna scaffolder", required = True )
    
    parser.add_argument( "--soapdenovo2_with_rascaf", help = "Enter the output for soapdenovo2 with rascaf", required = True )
    parser.add_argument( "--soapdenovo2_with_prna_scaffolder", help = "Enter the output for soapdenovo2 with prna scaffolder", required = True )
    
    parser.add_argument( "--abyss_with_rascaf", help = "Enter the output for abyss with rascaf", required = True )
    parser.add_argument( "--abyss_with_prna_scaffolder", help = "Enter the output for abyss with prna scaffolder", required = True )
    
    parser.add_argument( "--output_filename", help = "Enter the name of the outputfile in csv", required = True )
    
    parser.add_argument( "--threads", type = int, default = 1)
    return parser.parse_args()

def executeFGMP(genome_fasta, outputfilename, threads):
    
    cmd  = f" fgmp.pl "
    cmd += f" -g {genome_fasta}"
    cmd += f" -T {threads}"
    cmd += f" > {outputfilename}"
    os.system(cmd)

def main():
    """
    """
    options = parseCommandLineArguments()
    
    executeFGMP(options.masurca_with_rascaf, "masurca_with_rascaf_fgmp.output", options.threads)
    executeFGMP(f"{options.masurca_with_prna_scaffolder}/P_RNA_scaffolder.fasta", "masurca_with_prna_scaffolder_fgmp.output", options.threads)
    
    executeFGMP(options.megahit_with_rascaf, "megahit_with_rascaf_fgmp.output", options.threads)
    executeFGMP(f"{options.megahit_with_prna_scaffolder}/P_RNA_scaffolder.fasta", "megahit_with_prna_scaffolder_fgmp.output", options.threads)
    
    executeFGMP(options.soapdenovo2_with_rascaf, "soapdenovo2_with_rascaf_fgmp.output", options.threads)
    executeFGMP(f"{options.soapdenovo2_with_prna_scaffolder}/P_RNA_scaffolder.fasta", "soapdenovo2_with_prna_scaffolder_fgmp.output", options.threads)
        
    cmd = f"tar -xvhf {options.abyss_with_rascaf}"
    os.system(cmd)
    abyss_with_rascaf_files = glob.glob("abyss*rascaf*")
    
    cmd = f"tar -xvhf {options.abyss_with_rascaf}"
    os.system(cmd)
    abyss_with_prna_scaffolder_files = glob.glob("abyss*_p_rna_scaffolder*")
    
    for abyss_file in abyss_with_rascaf_files:
        executeFGMP(f"{abyss_file}", f"{abyss_file}_fgmp.output", options.threads)
    for abyss_file in options.abyss_with_prna_scaffolder_files:
        executeFGMP(f"{abyss_file}", f"{abyss_file}_fgmp.output", options.threads)
    

if __name__ == "__main__":
    main()